// Generated by https://quicktype.io

export interface MercadoLivreResponse {
  domain:                         string;
  user:                           string;
  isWillingToRelocate:            boolean;
  isUserAuthenticated:            boolean;
  isUserETXCandidate:             boolean;
  isDomainETX:                    boolean;
  isDomainVeteran:                boolean;
  signUpConfig:                   MercadoLivreDebug;
  getHelpButton:                  MercadoLivreDebug;
  isCareerPlannerEnabled:         boolean;
  enableRememberMeOption:         boolean;
  isMyApplicationsEnabled:        boolean;
  showVeteranEmployerSignUp:      boolean;
  enableUserPreferenceSelection:  boolean;
  isUserPreferenceApplied:        boolean;
  candidate:                      MercadoLivreCandidate;
  branding:                       MercadoLivreBranding;
  positions:                      MercadoLivrePosition[];
  debug:                          MercadoLivreDebug;
  count:                          number;
  countFilterByMatchScore:        null;
  location_user:                  string;
  location_used:                  string;
  locationInsights:               null;
  showWizard:                     number;
  disableLocationSearchDropdown:  boolean;
  pcsAutocompleteLocationEnabled: number;
  recommended_star_threshold:     number;
  mocTitle:                       null;
  fuzzyResultsReturned:           boolean;
  query:                          MercadoLivreQuery;
  userTitles:                     any[];
  isThinProfile:                  boolean;
  veteranProgramDetails:          any[];
  enableTargetedResume:           number;
  jobCardConfig:                  null;
  facetDisplaySort:               MercadoLivreFacetDisplaySort;
  facets:                         MercadoLivreFacets;
  locationRadiusConfig:           MercadoLivreLocationRadiusConfig;
  isSubQuery:                     boolean;
}

export interface MercadoLivreBranding {
  resumeOptional:                          number;
  showJobId:                               number;
  homePageHeroBanner:                      MercadoLivreHomePageHeroBanner;
  companyName:                             string;
  navBar:                                  MercadoLivreNavBar;
  custom_style:                            MercadoLivreCustomStyle;
  hideJobCart:                             boolean;
  favicons:                                MercadoLivreFavicons;
  i18n_overrides_master:                   MercadoLivreI18NOverridesMaster;
  privacy:                                 MercadoLivreBrandingPrivacy;
  enableTalentNetwork:                     number;
  talentNetworkBranding:                   MercadoLivreTalentNetworkBranding;
  talentNetworkHeroBanner:                 MercadoLivreTalentNetworkHeroBanner;
  recaptcha_enabled:                       number;
  showLoggedOutNotificationsPrivacyPolicy: boolean;
}

export interface MercadoLivreCustomStyle {
  font: string;
  css:  string;
}

export interface MercadoLivreFavicons {
  favicon: string;
}

export interface MercadoLivreHomePageHeroBanner {
  useImage:         number;
  opacity:          number;
  hideInMobileView: boolean;
  image:            string;
}

export interface MercadoLivreI18NOverridesMaster {
  internalPrivacy: MercadoLivreInternalPrivacy;
  privacy:         MercadoLivreI18NOverridesMasterPrivacy;
}

export interface MercadoLivreInternalPrivacy {
  es: MercadoLivreInternalPrivacyEn;
  pt: MercadoLivreInternalPrivacyEn;
  en: MercadoLivreInternalPrivacyEn;
}

export interface MercadoLivreInternalPrivacyEn {
  internalPrivacy_header: string;
  internalPrivacy_button: string;
  internalPrivacy_text:   string;
}

export interface MercadoLivreI18NOverridesMasterPrivacy {
  es: MercadoLivrePrivacyEn;
  pt: MercadoLivrePrivacyEn;
  en: MercadoLivrePrivacyEn;
}

export interface MercadoLivrePrivacyEn {
  privacy_header: string;
  privacy_button: string;
  privacy_text:   string;
}

export interface MercadoLivreNavBar {
  opacity:    number;
  color:      string;
  image:      string;
  link:       string;
  background: string;
  title:      string;
}

export interface MercadoLivreBrandingPrivacy {
  title:  string;
  button: string;
  text:   string;
}

export interface MercadoLivreTalentNetworkBranding {
  custom_html: MercadoLivreCustomHTML;
}

export interface MercadoLivreCustomHTML {
  header: string;
  footer: string;
}

export interface MercadoLivreTalentNetworkHeroBanner {
  useImage: number;
  opacity:  number;
}

export interface MercadoLivreCandidate {
  enc_id:              number;
  fullname:            string;
  firstname:           string;
  lastname:            string;
  skills:              any[];
  email:               string;
  phone:               string;
  location:            string;
  filename:            null;
  starred_positions:   any[];
  resumeUrl:           string;
  onboardingCompleted: boolean;
  isUserInPcsIjp:      boolean;
  linkedinUrl:         string;
}

export interface MercadoLivreDebug {
}

export interface MercadoLivreFacetDisplaySort {
  skills:      string;
  departments: string;
  seniority:   string;
  locations:   string;
}

export interface MercadoLivreFacets {
  skills:      { [key: string]: number };
  departments: { [key: string]: number };
  seniority:   MercadoLivreSeniority;
  locations:   { [key: string]: number };
}

export interface MercadoLivreSeniority {
  "Mid/Senior": number;
  Entry:        number;
  Intern:       number;
}

export interface MercadoLivreLocationRadiusConfig {
  showLocationRadius: number;
  locationRadiusType: string;
}

export interface MercadoLivrePosition {
  id:                   number;
  name:                 string;
  location:             string;
  locations:            string[];
  hot:                  number;
  department:           string;
  business_unit:        string;
  t_update:             number;
  t_create:             number;
  ats_job_id:           string;
  display_job_id:       string;
  type:                 string;
  id_locale:            string;
  job_description:      string;
  locale:               string;
  stars:                number;
  medallionProgram:     null;
  location_flexibility: null;
  work_location_option: null;
  canonicalPositionUrl: string;
}

export interface MercadoLivreQuery {
  query:      string;
  location:   string;
  department: any[];
  skill:      any[];
  seniority:  any[];
  pid:        string;
}
